# frozen_string_literal: true

source "https://rubygems.org"

git_source(:github) { |repo_name| "https://github.com/#{repo_name}" }

# Specify your gem's dependencies in solidus_dev_support.gemspec
gemspec

branch = ENV.fetch('SOLIDUS_BRANCH', 'master')
gem 'solidus', github: 'solidusio/solidus', branch: branch

# These gems will be used by the temporary extensions generated by tests
group :test do
  gem 'solidus_auth_devise'
  gem 'factory_bot', '> 4.10.0'
  gem 'mysql2'
  gem 'pg'
  gem 'sqlite3'
end
