# frozen_string_literal: true

source "https://rubygems.org"

git_source(:github) { |repo_name| "https://github.com/#{repo_name}" }

# Specify your gem's dependencies in solidus_dev_support.gemspec
gemspec

branch = ENV.fetch('SOLIDUS_BRANCH', 'master')
gem 'solidus', github: 'solidusio/solidus', branch: branch

# A workaround for https://github.com/bundler/bundler/issues/6677
gem 'rails', '>0.a'

# These gems will be used by the temporary extensions generated by tests
group :test do
  gem 'factory_bot', '> 4.10.0'
  gem 'mysql2'
  gem 'pg'
  gem 'solidus_auth_devise'
  gem 'sqlite3'
end

# Use a local Gemfile to include development dependencies that might not be
# relevant for the project or for other contributors, e.g.: `gem 'pry-debug'`.
eval_gemfile 'Gemfile-local' if File.exist? 'Gemfile-local'
