# frozen_string_literal: true

source "https://rubygems.org"

git_source(:github) { |repo_name| "https://github.com/#{repo_name}" }

# Specify your gem's dependencies in solidus_dev_support.gemspec
gemspec

branch = ENV.fetch('SOLIDUS_BRANCH', 'main')
gem 'solidus', github: 'solidusio/solidus', branch: branch

rails_version = ENV.fetch("RAILS_VERSION", "~> 7.0")
gem 'rails', rails_version

gem 'bundler'
gem 'rake'

# These gems will be used by the temporary extensions generated by tests
group :test do
  gem 'mysql2'
  gem 'pg'
  gem 'solidus_auth_devise'
  gem 'sqlite3', rails_version < '~> 7.2' ? '~> 1.4' : '~> 2.0'
end

# Use a local Gemfile to include development dependencies that might not be
# relevant for the project or for other contributors, e.g.: `gem 'pry-debug'`.
eval_gemfile 'Gemfile-local' if File.exist? 'Gemfile-local'

if rails_version == "~> 7.0"
  gem 'concurrent-ruby', '< 1.3.5'
end
